### ISSUE TITLE
Should we add nSkinz contributions to advancedfx credits?

### ISSUE THREAD

**Issue by dtugend** [advancedfx/contrib#4]
e.g.: https://github.com/advancedfx/nSkinz/pull/15
I am unsure myself, since it's not really advancedfx thing, but then again it's a repo under advnacedfx?

**Comment by xNWP** [comment]
I'd say credit them while specifying that we use a modified version of their code done by you

**Comment by dtugend** [comment]
nSkinz-advancedfx has been an independent project (that stopped when CS2 came along), that was not added to advancedfx / HLAE download, thus closing.
